# Generated by Django 4.0.4 on 2022-05-22 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payment_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('created_at', models.DateField()),
                ('payment_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payment_info.paymentinfo')),
            ],
        ),
    ]
